### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by andremald** [twinnydotdev/twinny#239]
Hi! I am trying to use the tool but somehow the code completion is  not working. The chat functionality works just fine so I am quite sure I configured the connectors properly. Unfortunately, I couldn't find any logging. Hence I am not even sure whether the completion request is being sent.

It tried the following models: codegemma, codellama and starcoder. ( always the fim version)

The path is /api/generate

Though it is also not working in a host vs code, I normally work inside a dev container one. Hence, I updated the hostname to host.docker.internal

As I said, the chat functionality works just fine. I am wondering what could be the issue with the coding completion one?

**Comment by rjmacarthy** [comment]
Hello,

Please confirm all settings used for FIM completion providers.  Also, please enable the debugging information in the settings, scroll to the bottom and tick enable logging, then go to Help -> Toggle Developer Tools inside Visual Studio Code to look out for any errors.

Many thanks,

**Comment by andremald** [comment]
Hi! While debugging I could see that there is a request being sent if I use the chat functionality. However, nothing shows up in the console for the code completion ( even when I request it with  Option + \ ( mac user ) )

I also found a 
"Problem creating default templates "/root/.twinny/templates""

Can it be that's the issue? No template-> no FIM?

**Comment by rjmacarthy** [comment]
Hey, that shouldn't be an issue for fim as they are built in.  Please provide all the provider configuration settings as previously requested.

**Comment by cold-eye** [comment]
![c41e9d3372f0fb5080c93d66b7a04fc9](https://github.com/rjmacarthy/twinny/assets/48782821/e4a6a4ca-5b3b-4f80-ae53-8138c75ca317)

**Comment by andremald** [comment]
Type: FIM
Fim template: codegemma
Provider: ollama
Protocol: http
Model name: codegemma:2b
Hostname: host.docker.internal
Port: 11434
Path: /api/generate

As I mentioned in the previous message, I don't get request in the console as you do ( based on your photo )

**Comment by rjmacarthy** [comment]
I would recommend trying codellama:7b-code to see if it works.

**Comment by andremald** [comment]
Just gave a try, still nothing:

Settings:
<img width="534" alt="Screenshot 2024-05-08 at 23 28 38" src="https://github.com/rjmacarthy/twinny/assets/42136531/846104d1-a0ed-41e8-844c-e161c7265ddd">

Console after a successful call to the chat api and several "Option + \ " in a python file:
<img width="545" alt="Screenshot 2024-05-08 at 23 33 52" src="https://github.com/rjmacarthy/twinny/assets/42136531/50e92853-909d-4ec9-a4ee-f298160135a6">

**Comment by dishbrains** [comment]
I have the same problem as you andremald, i.e. chat is working fine but FIM does nothing

I have a strange error logged when I type in my cpp file. is this causing it or is it unrelated?

![image](https://github.com/rjmacarthy/twinny/assets/157640122/5c766c37-910b-4156-bec6-7d0fe9f18c01)

**Comment by oregonpillow** [comment]
Same problem here. All settings correct. 13b or 7b, doesn't matter. Only chat seems to work. I see the robot icon loading when i start coding, but no autocomplete prompts ever how

**Comment by localbarrage** [comment]
Failing for me too. I can see the message being received by the provider, but no response and no error. I am using Aphrodite's openai api server. I have tried different providers, yet none give a resopnse.

**Comment by localbarrage** [comment]
My issue might partly related to there not being an actual supported OpenAi provider. I setup a litellm proxy to forward to my model and I am still not getting any completions.

**Comment by hitzhangjie** [comment]
+1

**Comment by jleivo** [comment]
Hi.

I have the same issue: chat works, FIM doesn't, no matter what I do in the configurations.

I was looking at the developer tools. as suggested, and when I was writing in the VScode I saw this in the Developer console

 ERR memory access out of bounds: RuntimeError: memory access out of bounds
	at wasm://wasm/000bc226:wasm-function[254]:0x2b979
	at Parser.parse (/home/juleivo/.vscode-server/extensions/rjmacarthy.twinny-3.11.39/out/index.js:2:218649)
	at t.CompletionProvider.provideInlineCompletionItems (/home/juleivo/.vscode-server/extensions/rjmacarthy.twinny-3.11.39/out/index.js:2:123675)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async B.provideInlineCompletions (/home/juleivo/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/out/vs/workbench/api/node/extensionHostProcess.js:155:108949)

twinny is being run in WSL Ubuntu 20.04 LTS

**Comment by KizzyCode** [comment]
Same issue, OS is macOS, provider is ollama with starcoder:3b – ollama gets request and does computation, but whatever is computed does not show up in VSCode...

**Comment by yuhanj2** [comment]
I found that setting Folding Range Provider in vscode settings to twinny would solve this issue for me, not sure if it will work for everyone.
<img width="736" alt="image" src="https://github.com/rjmacarthy/twinny/assets/55003495/b5fc919a-948b-4fdc-8002-d8df675f55f6">

**Comment by KizzyCode** [comment]
@yuhanj2 Thx, that workaround works for me too!

**Comment by GreatApo** [comment]
Same issue here. Could it be bugging out due to other extensions?

**Comment by rjmacarthy** [comment]
Hello all, do we have any indication of what is broken?  I have been using the extension myself recently and it's working with latest version of code.  Many thanks.

```
❯ code -v
1.90.2
5437499feb04f7a586f677b155b039bc2b3669eb
x64
```

**Comment by swedenSnow** [comment]
First of all, thank you for all your work @rjmacarthy 🙌🏽

I'm having the same issue, have a setup with ollama and just updated VSC to 1.90.2 and ollama 0.1.48
llama3 for chat ( working )
dolphincoder for FIM (I've tried with codellama, same issue)
![image](https://github.com/twinnydotdev/twinny/assets/31956031/6590d5ce-fd09-4ec0-adf6-f841152c2b62)

**Comment by rjmacarthy** [comment]
Hello, I think starcoder 2 is not good for fim completion I tried it. Please try one of the recommended models in the docs. Many thanks.

**Comment by swedenSnow** [comment]
Thanks for the heads up. Was working ok but now looking at the logs it seems trying to get a model I dont have locally anymore: "model": "deepseek-coder:1.3b-base-fp16", even when I changed provider to codellama.
![image](https://github.com/twinnydotdev/twinny/assets/31956031/2900861f-a0f9-44bf-9edd-00013132cb29)

**Comment by rjmacarthy** [comment]
Maybe try to restart ide.

**Comment by swedenSnow** [comment]
I have. Its a bit confusing now: I installed the deepseek model as mentioned above, and then my FIM started working althogh still not requiring the model I have entered as provider (codellama) but deepseek again 🤔 
***Twinny Stream Debug***
Streaming response from 0.0.0.0:11434.
Request body:
  "model": "deepseek-coder:1.3b-base-fp16",
  "prompt": "<｜fim▁begin｜>/**/\n\n/* Language: Typescript React (typescriptreact) */\n/* File uri
  
![image](https://github.com/twinnydotdev/twinny/assets/31956031/7c38eef1-4cd0-47ed-b19b-ab927e15300a)

**Comment by GreatApo** [comment]
> Hello all, do we have any indication of what is broken? I have been using the extension myself recently and it's working with latest version of code. Many thanks.
> 

To start with, thank you for you work!

I was getting the following error upon writing code:
![image](https://github.com/twinnydotdev/twinny/assets/9620510/1af3f369-8154-4af7-8fd5-d75d89752e8f)

I disabled-enabled the extension, and now it prints the request, but nothing happens:
![image](https://github.com/twinnydotdev/twinny/assets/9620510/648d6d45-0047-4ad1-999c-728096f486c9)
![image](https://github.com/twinnydotdev/twinny/assets/9620510/fb58eed5-c2ef-4f7c-897c-5fd458fc8158)

Then, after a while, the following errors appear:
![image](https://github.com/twinnydotdev/twinny/assets/9620510/920f06ff-4eba-4b33-b06c-bb61f0558ebe)

The chat works...
![image](https://github.com/twinnydotdev/twinny/assets/9620510/a3f2daae-b875-4480-897b-984213897558)

VSCode info:
![image](https://github.com/twinnydotdev/twinny/assets/9620510/4e8f7a15-f7db-42da-a1dc-6992dc41a7a6)

**Comment by fredrikburmester** [comment]
I also have the issue of FIM not working. Running Ollama locally on M3 Mac.
VSCode Version: 1.91.0
<img width="439" alt="Screenshot 2024-07-04 at 21 41 45" src="https://github.com/twinnydotdev/twinny/assets/26228321/32642ac2-7279-4330-98ac-c14df9cc34d2">

**Comment by fredrikburmester** [comment]
This is the error in the console:
```
ERR Cannot read properties of undefined (reading 'apply'): TypeError: Cannot read properties of undefined (reading 'apply')
    at wasmImports.<computed>.stub.e.<computed> (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:177464)
    at null.<anonymous> (wasm://wasm/0003dbda:1:39736)
    at null.<anonymous> (wasm://wasm/0003dbda:1:35226)
    at postInstantiation (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:178474)
    at /Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:178735
    at t.getParser (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:114775)
    at t.CompletionProvider.provideInlineCompletionItems (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:123581)
    at J.provideInlineCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:119139)
```

**Comment by arungithub9** [comment]
> This is an error in the console:
> 
> ```
> ERR Cannot read properties of undefined (reading 'apply'): TypeError: Cannot read properties of undefined (reading 'apply')
>     at wasmImports.<computed>.stub.e.<computed> (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:177464)
>     at null.<anonymous> (wasm://wasm/0003dbda:1:39736)
>     at null.<anonymous> (wasm://wasm/0003dbda:1:35226)
>     at postInstantiation (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:178474)
>     at /Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:178735
>     at t.getParser (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:114775)
>     at t.CompletionProvider.provideInlineCompletionItems (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:123581)
>     at J.provideInlineCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:119139)
> ```
> 
> Also:
> 
> ```
> ERR Parsing failed: Error: Parsing failed
>     at Parser.parse (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:218987)
>     at t.CompletionProvider.provideInlineCompletionItems (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.11.43/out/index.js:2:123675)
>     at J.provideInlineCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:119139)
> ```

I am facing the same error with VS Code Ver 1.90.2.

**Comment by rjmacarthy** [comment]
I just released a new version which adds a try catch to the parsing of the document to attempt to fix this problem.  Please let me know if it helps, if not it would be helpful to know what file/language/extension is being used when this error appears.  Many thanks.

**Comment by Hezkore** [comment]
I couldn't get a manual suggestion to trigger, not by the command nor the keybind.
However, disabling auto suggestion made the manual trigger work just fine.
`"twinny.autoSuggestEnabled": false` in settings.

**Comment by atljoseph** [comment]
I installed latest version extension today. Configured an embedding, chat, and fim provider with proper models. Embedding was stuck and never ever ever completed (no requests caused Ollama to load model). No completion ever happened. It was with qwen2.5 coder. If I’m using the wrong one for FIM, then maybe the software should say that?! I see completion requests in debug console. None of the debugs had actually helpful information.

**Comment by rjmacarthy** [comment]
Hey @atljoseph,

Thank you for reaching out and sharing your experience with our extension. I'm sorry to hear you're facing issues, especially when you've taken the time to set everything up.

This project is a personal endeavour, and while I strive to ensure broad compatibility, each case's unique configuration can sometimes lead to unexpected behaviours...

**Comment by Pspritechologist** [comment]
I'm having the same issue of chat working fine, but FIM not working at all. 
I have FIM configured to use codellama:7b-code, when code completion triggers I see the following error in the debugger:
```
cannot open file:///extension-output-rjmacarthy.twinny-%231-Twinny. Detail: Unable to read file '/extension-output-rjmacarthy.twinny-#1-Twinny' (Error: Unable to resolve nonexistent file '/extension-output-rjmacarthy.twinny-#1-Twinny'): CodeExpectedError: cannot open file:///extension-output-rjmacarthy.twinny-%231-Twinny. Detail: Unable to read file '/extension-output-rjmacarthy.twinny-#1-Twinny' (Error: Unable to resolve nonexistent file '/extension-output-rjmacarthy.twinny-#1-Twinny')
    at DOe.$tryOpenDocument (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:619:8481)
```
I recall seeing something in the Twinny output in VSCode itself once but I can't seem to repeat that.

**Comment by joxxoxo** [comment]
I also had error with ` ERR cannot open file:///extension-output-rjmacarthy.twinny-%232-Twinny. `.
Downgrading twinny to 3.17.19 seems to help

**Comment by rjmacarthy** [comment]
Thanks @joxxoxo and @Pspritechologist what os etc are you using?

**Comment by joxxoxo** [comment]
@rjmacarthy 
macbook, sequoia (15.0.1) 
I've tried reinstalling the extension, removing `~/.twinny` folder, reverting settings to defaults, using codellama:7b code+instruct models.

vscode info (latest):
```
Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z (6 days ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
```

PS thank you for the great extension btw

**Comment by rjmacarthy** [comment]
Hey @joxxoxo thanks for the response, it's interesting that 3.17.19 works, does `3.17.20` or `3.17.21` break it for you then?

Many thanks!

**Comment by joxxoxo** [comment]
Yes, I've tried many versions yesterday and 3.17.19 was the latest working for me

**Comment by joxxoxo** [comment]
I saw some changes in src/common/logger.ts in the next version and thought it can be the reason

**Comment by joxxoxo** [comment]
FIM is working in 3.17.27 🙌 
I don't see Twinny in Output options though 🤷

**Comment by Pspritechologist** [comment]
> Thanks @joxxoxo and @Pspritechologist what os etc are you using?

I'm using Arch but some time later (after a restart or two) I opened VSCode and FIM was just working. No idea why.

**Comment by phyzical** [comment]
for me what made code completion work was to use Fim Template: automatic
