### ISSUE TITLE
Chat not working no matter the model used

### ISSUE THREAD

**Issue by machisuji** [twinnydotdev/twinny#315]
**Describe the bug**
I've been trying to get the chat to work with llama3, llama3.1, mistral, codellama:7b-instruct, codegemma:7b-instruct but it always fails ("Sorry, I don't understand").

**To Reproduce**
Install latest VS Code and twinny extension. Try using any of the models above via ollama.

**Expected behavior**
The chat should work.

**Screenshots**

**Logging**
Rnable logging in the extension settings if not already enabled (you may need to restart vscode if you don't see logs).  Proivide the log with the report.

twinny logs:

```
2024-09-13 15:12:48.851 [error] [Extension Host] Error parsing JSON: TypeError: Cannot read properties of undefined (reading '0')
	at getChatDataFromProvider (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:73226:27)
	at ChatService.onStreamData (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:84602:22)
	at onData (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:84894:41)
	at Object.transform (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:73744:26)
	at ensureIsPromise (node:internal/webstreams/util:185:19)
	at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:515:18)
	at node:internal/webstreams/transformstream:560:16
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```	

ollama logs:

```
[GIN] 2024/09/13 - 14:17:45 | 200 |  2.128053804s |      172.17.0.1 | POST     "/api/chat"
[GIN] 2024/09/13 - 14:17:46 | 200 |  631.029488ms |      172.17.0.1 | POST     "/api/chat"
```

**API Provider**
ollama

**Chat or Auto Complete?**
chat

**Model Name**
llama3, llama3.1, mistral, codellama:7b-instruct, codegemma:7b-instruct

**Desktop (please complete the following information):**
 - OS: Windows 11, WSL2, ollama running under Linux
 - VS Code 1.93.1
 - twinny version v3.16.2

**Additional context**

**Comment by MaKTaiL** [comment]
I'm having the same issue. I heard this is a problem from a recent version of Ollama.

**Comment by Bombfuse** [comment]
I've also tried other ollama versions down to 0.3.7 and were unable to get those to work

**Comment by akpatternica** [comment]
the same :(

**Comment by rjmacarthy** [comment]
Hey all, my mistake I updated the default chat path and it was wrong, plus I have been away for a week which left it broken.  I just released a fixed version.  Many thanks.

**Comment by JJones780** [comment]
For me I was getting a 404 error in the chat window and the rope error from the ollama server.
_To save other new users from a little bit extra frustration:_
`To get to the "reset providers" use the little "electrical plug" icon along the top of the Twinny chat window with popup description "twinny providers".`
