### ISSUE TITLE
Open WebUI update

### ISSUE THREAD

**Issue by unclemusclez** [twinnydotdev/twinny#329]
Open WebUI just updated their project to be more compatible with the Ollama API backend for embeddings. I think it broke something with twinny

```
[Extension Host] [twinny] ***Twinny Stream Debug***
Streaming response from 127.0.0.1:8100.
Request body:
{
  "model": "llama3.1:70b-instruct-q2_K",
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "test"
    },
    {
      "role": "user",
      "content": "\n  Generate a title for this conversation in under 10 words.\n  It should not contain any special characters or quotes.\n"
    }
  ],
  "keep_alive": -1,
  "options": {
    "temperature": 0.5,
    "num_predict": 128
  }
}


Request options:
{
  "hostname": "127.0.0.1",
  "port": 8100,
  "path": "/ollama/api/generate",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer ****"
  }
}


Number characters in all messages = 123
console.ts:137 [Extension Host] [twinny] ***Twinny Stream Debug***
Streaming response from 127.0.0.1:8100.
Request body:
{
  "model": "llama3.1:70b-instruct-q2_K",
  "stream": true,
  "messages": [
    {
      "role": "system",
      "content": "You are a perfect Python developer. You are a perfect Bash developer. You always\nuse Python or Bash. You speak in English, Python, and Bash. You use perfect and\nconcise style when coding. You carefully choose the code you write. You will be a\nhelpful, respectful and honest coding assistant. Always reply using markdown. Be\nclear and concise, prioritizing brevity in your responses. For code refactoring,\nuse markdown with appropriate code formatting. You always reply with using\nmarkdown. You use markdown with code formatting for code refactoring."
    },
    {
      "role": "user",
      "content": "test"
    }
  ],
  "keep_alive": -1,
  "options": {
    "temperature": 0.5,
    "num_predict": 128
  }
}


Request options:
{
  "hostname": "127.0.0.1",
  "port": 8100,
  "path": "/ollama/api/generate",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer ***"
  }
}


Number characters in all messages = 548
log.ts:439   ERR [Extension Host] Fetch error: Error: Server responded with status code: 422
	at streamResponse (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.17/out/index.js:73798:13)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
console.ts:137 [Extension Host] Fetch error: Error: Server responded with status code: 422
	at streamResponse (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.17/out/index.js:73798:13)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

the above issue may have been due to mixing up the chat and generate APIs for FIM and Chat

however, now i am here: 
```
console.ts:137 [Extension Host] Error parsing JSON: TypeError: Cannot read properties of undefined (reading '0')
	at getChatDataFromProvider (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.17/out/index.js:73256:27)
	at ChatService.onStreamData (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.17/out/index.js:84682:22)
	at onData (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.17/out/index.js:84974:41)
	at Object.transform (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.17/out/index.js:73818:26)
	at ensureIsPromise (node:internal/webstreams/util:185:19)
	at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:515:18)
	at transformStreamDefaultSinkWriteAlgorithm (node:internal/webstreams/transformstream:565:10)
	at Object.write (node:internal/webstreams/transformstream:360:14)
	at ensureIsPromise (node:internal/webstreams/util:185:19)
	at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1112:5)
	at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1227:5)
	at writableStreamDefaultControllerWrite (node:internal/webstreams/writablestream:1101:3)
	at writableStreamDefaultWriterWrite (node:internal/webstreams/writablestream:991:3)
	at [kChunk] (node:internal/webstreams/readablestream:1554:31)
	at readableStreamFulfillReadRequest (node:internal/webstreams/readablestream:2096:24)
	at readableStreamDefaultControllerEnqueue (node:internal/webstreams/readablestream:2287:5)
	at transformStreamDefaultControllerEnqueue (node:internal/webstreams/transformstream:496:5)
	at TransformStreamDefaultController.enqueue (node:internal/webstreams/transformstream:306:5)
	at Object.transform (node:internal/webstreams/encoding:156:22)
	at ensureIsPromise (node:internal/webstreams/util:185:19)
	at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:515:18)
	at transformStreamDefaultSinkWriteAlgorithm (node:internal/webstreams/transformstream:565:10)
	at Object.write (node:internal/webstreams/transformstream:360:14)
	at ensureIsPromise (node:internal/webstreams/util:185:19)
	at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1112:5)
	at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1227:5)
	at writableStreamDefaultControllerWrite (node:internal/webstreams/writablestream:1101:3)
	at writableStreamDefaultWriterWrite (node:internal/webstreams/writablestream:991:3)
	at [kChunk] (node:internal/webstreams/readablestream:1554:31)
	at readableStreamFulfillReadRequest (node:internal/webstreams/readablestream:2096:24)
	at readableByteStreamControllerEnqueue (node:internal/webstreams/readablestream:2811:7)
	at ReadableByteStreamController.enqueue (node:internal/webstreams/readablestream:1181:5)
	at fetchParams.controller.resume (node:internal/deps/undici/undici:10452:47)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async pullAlgorithm (node:internal/deps/undici/undici:10400:9)
```

**Comment by rjmacarthy** [comment]
Hey. For chat you should be using `/ollama/v`/chat/completions`, right?

**Comment by unclemusclez** [comment]
@rjmacarthy i am getign a little confused toward which endpoints are the right ones at the moment. i think multiple work,

that beng said, the same issue has occurred:
[Extension Host] [twinny] ***Twinny Stream Debug***
Streaming response from webui.kamala:443.
Request body:
{
  "model": "llama3.1:70b-instruct-q2_K",
  "stream": true,
  "messages": [
    {
      "role": "system",
      "content": "You are a perfect Python developer. You are a perfect Bash developer. You always\nuse Python or Bash. You speak in English, Python, and Bash. You use perfect and\nconcise style when coding. You carefully choose the code you write. You be a\nhelpful, respectful and honest coding assistant. Always reply using markdown. Be\nclear and concise, prioritizing brevity in your responses. For code refactoring,\nuse markdown with appropriate code formatting. You always reply with using\nmarkdown. You use markdown with code formatting for code refactoring."
    },
    {
      "role": "user",
      "content": "Explain the following code;\npg.run()\nDo not waffle on. The language is:\nPython"
    }
  ],
  "keep_alive": -1,
  "options": {
    "temperature": 0.5,
    "num_predict": 128
  }
}


Request options:
{
  "hostname": "webui.kamala",
  "port": 443,
  "path": "/ollama/api/chat",
  "protocol": "https",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "***"
  }
}


Number characters in all messages = 622
log.ts:439   ERR [Extension Host] Fetch error: TypeError: fetch failed
	at node:internal/deps/undici/undici:12502:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async streamResponse (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.18/out/index.js:73816:22)
console.ts:137 [Extension Host] Fetch error: TypeError: fetch failed
	at node:internal/deps/undici/undici:12502:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async streamResponse (/home/musclez/.vscode-server/extensions/rjmacarthy.twinny-3.17.18/out/index.js:73816:22)
C @ console.ts:137
log.ts:429  WARN [mainThreadStorage] large extension state detected (extensionId: rjmacarthy.twinny, global: true): 1147.830078125kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.
```

**Comment by rjmacarthy** [comment]
Hey, I am not sure sorry of different api configs for every individual.  After a few seconds of google and according to the docs at https://docs.openwebui.com/getting-started/api#-chat-completions it should be like this:  

```
http://localhost:3000/api/chat/completions
```

Closing this issue as it's not really an issue and more of a support for individual basis.

**Comment by unclemusclez** [comment]
just to confirm, you are able to have twinny contact chat, generate, and embed API endpoints as of the of recent update?

**Comment by rjmacarthy** [comment]
Yes I am able, but I use ollama not ollama web ui.

**Comment by unclemusclez** [comment]
> Yes I am able, but I use ollama not open web ui.

as i understand it, ollama uses `/api/generate`, `/api/chat,` and `/api/embed`
open-webui uses  `/ollama/api/generate`, `/ollama/api/chat,` and `/ollama/api/embed`

Now, there are variations in this because both work with openAI's API, but for actually testing everything, i was using the above, and then checking against that. 

i do think there is an issue with the embedding menu in particular. https://github.com/twinnydotdev/twinny/issues/334
and there seems to be a new structure to open-webui api's itnegration with ollama. https://github.com/open-webui/open-webui/releases/tag/v0.3.30

on a side note, for personal use, i would really look into open-webui. it's phenomenal. and in theory, one should be able to share the same vector between Open-WebUI, Twinny, and Open Hands/Open Devin. that is my goal.

**Comment by unclemusclez** [comment]
![image](https://github.com/user-attachments/assets/5a371481-6f1b-4a17-8324-18d04213c238)
seems fixed in recent dev branch of open-webui... major league shout out to @Peter-De-Ath
