### ISSUE TITLE
embedding doesn't work

### ISSUE THREAD

**Issue by jurykor** [twinnydotdev/twinny#387]
I just found out that from version 3.18.5 embedding doesn't work well.

Let's take this as an example of the "twinny" repository.

In version 3.18.4, if I run the `explain @extension.global.d.ts`, I'm getting a file analysis:
![3-18-4](https://github.com/user-attachments/assets/d501f532-b7d3-4825-bb3b-e022c05b7e5a)

But in versions 3.18.5 and later, I just get "reflections on the topic":
![3-18-5](https://github.com/user-attachments/assets/d4e65a0d-491a-4b75-8f8c-f75b3913d2fa)

So I had to roll back to 3.18.4...

**Comment by fishshi** [comment]
I tried 3.19.0, and it seems that this issue does exist. I haven't looked at the code in detail yet, but I suspect it might be related to the fileContents that was removed in a710b6b.

**Comment by jurykor** [comment]
in version 3.19.0, the embedding process does not start processing (I waited a long time without recording):


https://github.com/user-attachments/assets/425d2f16-98e9-4ae1-9180-38797ef50073

**Comment by rjmacarthy** [comment]
Thanks for the detailed report. It seems related to this issue: https://github.com/twinnydotdev/twinny/issues/386 Will be investigating soon, since we removed some default ignored file list (in favour of user defined) we have some crashes.  Are there any errors in the console?  Help > Toggler Developer Tools.

Many thanks!

**Comment by jurykor** [comment]
I'll take a look now. There is only one moment at once - all the files in the folder (from the video) are less than 100 lines.

**Comment by jurykor** [comment]
```
2024-11-13 15:08:14.755 [error] [Extension Host] Fetch error: TypeError: Cannot read properties of undefined (reading '0')
	at EmbeddingDatabase.getEmbeddingFromResponse (c:\Users\JuriKor\.vscode\extensions\rjmacarthy.twinny-3.19.0-win32-x64\out\index.js:57898:31)
	at onData (c:\Users\JuriKor\.vscode\extensions\rjmacarthy.twinny-3.19.0-win32-x64\out\index.js:57787:24)
	at fetchEmbedding (c:\Users\JuriKor\.vscode\extensions\rjmacarthy.twinny-3.19.0-win32-x64\out\index.js:57697:5)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by rjmacarthy** [comment]
Please provide API details of embedding API for ollama.

**Comment by jurykor** [comment]
> Please provide API details of embedding provider API for ollama. Please make sure it's `/api/embed` as described here it's the new standard it replaced the old API endpoint: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings

Thanks, it helped. The problem with the implementation process is coming to an end, but the initial problem still remains. However, as far as I understand, this problem will be solved with [#389](https://github.com/twinnydotdev/twinny/pull/389)
